export default () => ({
  ZOOM_MEETING_SDK_KEY: process.env.ZOOM_MEETING_SDK_KEY,
  ZOOM_MEETING_SDK_SECRET: process.env.ZOOM_MEETING_SDK_SECRET,

  ZOOM_API_BASE_URL: process.env.ZOOM_API_BASE_URL,
  ZOOM_OAUTH_ENDPOINT: process.env.ZOOM_OAUTH_ENDPOINT,
  ZOOM_ACCOUNT_ID: process.env.ZOOM_ACCOUNT_ID,
  ZOOM_CLIENT_ID: process.env.ZOOM_CLIENT_ID,
  ZOOM_CLIENT_SECRET: process.env.ZOOM_CLIENT_SECRET,
});
